from turtle import Turtle, Screen
huzi = Turtle()
huzi.shape("turtle")
huzi.color("pale violet red","firebrick")
huzi.pensize(5)
huzi.speed(4)
huzi.penup()
huzi.goto(-300, 0)
huzi.pendown()

def right_run():
    huzi.forward(100)
    huzi.right(90)


def move(dis):
    huzi.penup()
    huzi.forward(dis)
    huzi.pendown()


def down(dis):
    huzi.right(90)
    huzi.forward(dis)


def up(distance):
    huzi.backward(distance)


huzi.right(90)
huzi.forward(150)
huzi.penup()
huzi.backward(50)
huzi.pendown()
huzi.left(90)
right_run()
huzi.forward(50)
huzi.backward(150)
huzi.forward(150)

huzi.penup()
huzi.left(135)
huzi.forward(100)
huzi.pendown()
huzi.right(135)
huzi.forward(70)
huzi.left(90)
huzi.forward(50)
huzi.left(90)
huzi.forward(70)
huzi.penup()
huzi.right(90)
huzi.forward(30)
huzi.pendown()
huzi.forward(100)
huzi.right(135)
huzi.forward(100)
huzi.left(135)
huzi.forward(80)
huzi.penup()
huzi.forward(30)
huzi.left(90)
huzi.pendown()
huzi.forward(80)
huzi.penup()
huzi.forward(30)
huzi.dot(20)
huzi.penup()
huzi.forward(30)


# huzii = Turtle()
# huzii.shape("turtle")
# huzii.color("pale violet red","firebrick")
# huzii.pensize(5)
# huzii.penup()
# huzii.goto(-300, 0)
# huzii.pendown()
# huzii.right(90)
# huzii.forward(100)
# huzii.penup()
# huzii.backward(50)
# huzii.pendown()
# huzii.left(135)
# huzii.forward(70)
# huzii.backward(70)
# huzii.right(90)
# huzii.forward(70)
# huzii.left(45)
# huzii.penup()
# huzii.forward(30)
# huzii.pendown()
# huzii.left(65)
# huzii.forward(100)
# huzii.right(135)
# huzii.forward(100)
# huzii.backward(50)
# huzii.right(110)
# huzii.forward(35)
# huzii.penup()
# huzii.left(90)
# huzii.forward(50)
# huzii.left(90)
# huzii.forward(100)
# huzii.pendown()
#
# huzii.left(65)
# huzii.forward(90)
# huzii.backward(90)
# huzii.left(50)
# huzii.forward(90)
# huzii.backward(90)
# huzii.right(115)
# huzii.penup()
# huzii.forward(90)
# huzii.pendown()
#
#
#
# huzii.left(90)
# huzii.forward(50)
# huzii.left(45)
# huzii.forward(50)
# huzii.backward(50)
# huzii.right(90)
# huzii.forward(50)
# huzii.backward(50)
# huzii.right(135)
# huzii.forward(50)
# huzii.left(90)
# huzii.penup()
# huzii.forward(80)
# huzii.pendown()
#
# huzii.left(65)
# huzii.forward(100)
# huzii.right(135)
# huzii.forward(100)
# huzii.backward(50)
# huzii.right(110)
# huzii.forward(35)
# huzii.penup()
# huzii.left(90)
# huzii.forward(50)
# huzii.left(90)
# huzii.forward(100)
# huzii.pendown()

screen = Screen()
screen.exitonclick()
